version: "3"

services:
  app:
    build: .
    image: platziapp
    environment:
      MONGO_URL: "mongodb://db:27017/test"
    depends_on:
      - db
    ports:
      - "3000-3010:3000"
    volumes:
      - ".:/Users/jose+rubilar/src"
      - "/Users/jose+rubilar/src/node_mudules"
  db:
    image: mongo
